# Generated by Django 4.2.7 on 2023-11-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='heading',
            new_name='headline',
        ),
    ]
